user-info microservice #60
airavata-courses/Panorama pull request #64
Opened 2021-02-15 02:28 UTC by surajp28

2021-02-15 15:06 UTC, visheshdembla requested changes

2021-02-15 15:06 UTC, visheshdembla commented on user-service/api/routes/user.js
> +      //       res.status(404).json({
could you remove all the unnecessary comments

2021-02-15 15:06 UTC, visheshdembla commented on user-service/api/routes/user.js
> +5. We are using express framework for nodeJs
and these as well

2021-02-15 15:06 UTC, visheshdembla commented on user-service/app.js
> +//nodemon was used so that we dont need to restart the service by stopping it again and starting
here as well

2021-02-18 18:52 UTC, visheshdembla commented
@surajp28 are the changes for the service done or should I take care of these while converting the service to gRPC?

2021-02-18 19:06 UTC, surajp28 commented
@surajp28 Sorry I couldnt finish these changes. Could you handle them while converting the service to gPRC?

2021-02-18 21:41 UTC, visheshdembla commented
will make the changes as part of the next issue created to convert the service to a gRPC based one

2021-02-18 21:41 UTC, visheshdembla approved these changes

2021-02-18 21:41 UTC, merged